/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Frognas
 */
public class IngresarPuntajes extends javax.swing.JFrame {

    /**
     * Creates new form IngresarPuntajes
     */
    public IngresarPuntajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiana = new javax.swing.JLabel();
        jLabelBoton1 = new javax.swing.JLabel();
        jLabelBoton2 = new javax.swing.JLabel();
        jLabelBoton3 = new javax.swing.JLabel();
        jLabelBoton4 = new javax.swing.JLabel();
        jLabelBoton5 = new javax.swing.JLabel();
        jLabelBoton6 = new javax.swing.JLabel();
        jLabelBoton7 = new javax.swing.JLabel();
        jLabelBoton8 = new javax.swing.JLabel();
        jLabelBoton9 = new javax.swing.JLabel();
        jLabelBoton10 = new javax.swing.JLabel();
        jLabelRonda = new javax.swing.JLabel();
        jLabelInsertarPuntaje1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DianaF.png"))); // NOI18N
        getContentPane().add(jLabelDiana, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 500, 590));

        jLabelBoton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        getContentPane().add(jLabelBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabelBoton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        getContentPane().add(jLabelBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabelBoton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        getContentPane().add(jLabelBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabelBoton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(jLabelBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabelBoton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.1.png"))); // NOI18N
        getContentPane().add(jLabelBoton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabelBoton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        getContentPane().add(jLabelBoton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabelBoton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N
        getContentPane().add(jLabelBoton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabelBoton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N
        getContentPane().add(jLabelBoton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabelBoton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9.png"))); // NOI18N
        getContentPane().add(jLabelBoton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jLabelBoton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N
        getContentPane().add(jLabelBoton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        jLabelRonda.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabelRonda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRonda.setText("Ronda ");
        getContentPane().add(jLabelRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 360, 80));

        jLabelInsertarPuntaje1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabelInsertarPuntaje1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInsertarPuntaje1.setText("Inserte su puntaje :");
        getContentPane().add(jLabelInsertarPuntaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 80));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarPuntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBoton1;
    private javax.swing.JLabel jLabelBoton10;
    private javax.swing.JLabel jLabelBoton2;
    private javax.swing.JLabel jLabelBoton3;
    private javax.swing.JLabel jLabelBoton4;
    private javax.swing.JLabel jLabelBoton5;
    private javax.swing.JLabel jLabelBoton6;
    private javax.swing.JLabel jLabelBoton7;
    private javax.swing.JLabel jLabelBoton8;
    private javax.swing.JLabel jLabelBoton9;
    private javax.swing.JLabel jLabelDiana;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInsertarPuntaje1;
    private javax.swing.JLabel jLabelRonda;
    // End of variables declaration//GEN-END:variables
}
