/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sql.DBQuery;
import entidades.Ronda;

/**
 *
 * @author Frognas
 */
public class IngresarPuntajes1 extends javax.swing.JFrame {
Usuario user;
    /**
     * Creates new form IngresarPuntajes
     */
    public IngresarPuntajes1(Usuario user) {
        this.user = user;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiana = new javax.swing.JLabel();
        jLabelRonda = new javax.swing.JLabel();
        jLabelInsertarPuntaje1 = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        jComboBoxLanzamiento3 = new javax.swing.JComboBox<>();
        lblLanzamiento1 = new javax.swing.JLabel();
        lblLanzamiento2 = new javax.swing.JLabel();
        jComboBoxLanzamiento1 = new javax.swing.JComboBox<>();
        jComboBoxLanzamiento2 = new javax.swing.JComboBox<>();
        lblLanzamiento4 = new javax.swing.JLabel();
        lblRegresar1 = new javax.swing.JLabel();
        lblRegresar2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DianaF.png"))); // NOI18N
        getContentPane().add(jLabelDiana, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 500, 590));

        jLabelRonda.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabelRonda.setText("Ronda ");
        getContentPane().add(jLabelRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 360, 80));

        jLabelInsertarPuntaje1.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabelInsertarPuntaje1.setText("Inserte su puntaje :");
        getContentPane().add(jLabelInsertarPuntaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 80));

        lblRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        jComboBoxLanzamiento3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 120, -1));

        lblLanzamiento1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        lblLanzamiento1.setText("1° Lanzamiento:");
        getContentPane().add(lblLanzamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 220, 50));

        lblLanzamiento2.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        lblLanzamiento2.setText("2° Lanzamiento:");
        getContentPane().add(lblLanzamiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 220, 50));

        jComboBoxLanzamiento1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 120, -1));

        jComboBoxLanzamiento2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jComboBoxLanzamiento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxLanzamiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLanzamiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxLanzamiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 120, -1));

        lblLanzamiento4.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        lblLanzamiento4.setText("3° Lanzamiento:");
        getContentPane().add(lblLanzamiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 220, 50));

        lblRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresar1MouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        lblRegresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblRegresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresar2MouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
          this.setVisible(false);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void jComboBoxLanzamiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento3ActionPerformed

    private void jComboBoxLanzamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento1ActionPerformed

    private void jComboBoxLanzamiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLanzamiento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLanzamiento2ActionPerformed

    private void lblRegresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegresar2MouseClicked

    private void lblRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegresar1MouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

           DBQuery query = new DBQuery();
           Ronda ronda = new Ronda();
            try{
                if (query.registrarRonda(jComboBoxLanzamiento1.getSelectedIndex(), jComboBoxLanzamiento2.getSelectedIndex(), jComboBoxLanzamiento3.getSelectedIndex())) {
                    JOptionPane.showMessageDialog(this, "Ronda agregada exitosamente!.", "Succes", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al consultar la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch(Exception e){
                e.printStackTrace();              
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> jComboBoxLanzamiento1;
    private javax.swing.JComboBox<String> jComboBoxLanzamiento2;
    private javax.swing.JComboBox<String> jComboBoxLanzamiento3;
    private javax.swing.JLabel jLabelDiana;
    private javax.swing.JLabel jLabelInsertarPuntaje1;
    private javax.swing.JLabel jLabelRonda;
    private javax.swing.JLabel lblLanzamiento1;
    private javax.swing.JLabel lblLanzamiento2;
    private javax.swing.JLabel lblLanzamiento4;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblRegresar1;
    private javax.swing.JLabel lblRegresar2;
    // End of variables declaration//GEN-END:variables
}
