/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import entidades.Usuario;

/**
 *
 * @author Frognas
 */
public class Menu extends javax.swing.JFrame {
    
    private Usuario user;

    /**
     * Creates new form Menu
     */
    public Menu(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelCerrarSesion = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jLabelReportes = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 890, 10));

        jLabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jLabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabelPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/score.png"))); // NOI18N
        jLabelPuntaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPuntajeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabelReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        jLabelReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReportesMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPuntajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPuntajeMouseClicked
        // TODO add your handling code here:
        new IngresarPuntajes1(user).setVisible(true);
       
    }//GEN-LAST:event_jLabelPuntajeMouseClicked

    private void jLabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        user = null;
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelCerrarSesionMouseClicked

    private void jLabelReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReportesMouseClicked
        // TODO add your handling code here:
        new Reportes().setVisible(true);
        
    }//GEN-LAST:event_jLabelReportesMouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelReportes;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
